[project]
name = "footballscraper"
version = "0.1.0"
description = "Application to scrape football data from top 5 leagues in Europe"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "cloudscraper>=1.2.71",
    "pandas>=2.3.1",
    "psycopg>=3.2.9",
]
